name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Restore Main Dart Code
      run: |
        mkdir -p temp_backup
        cp lib/main.dart temp_backup/main.dart
        flutter create . --org com.jmphotoshop --project-name jm_photo_shop --overwrite
        cp temp_backup/main.dart lib/main.dart

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: JM-Photo-Shop-APK
        path: build/app/outputs/flutter-apk/app-release.apk
